### ISSUE TITLE
Write nicer guides: short and sweet

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vlasovskikh/funcparserlib#28]
```
Current tutorials are too big and outdated.

To use as exampels: nested brackets, Lisp S-Exprs and JSON.

Format: rst.

```

Original issue reported on code.google.com by `andrey.vlasovskikh` on 26 May 2011 at 11:30

**Comment by vlasovskikh** [comment]
Added the new [Getting Started](https://funcparserlib.pirx.ru/getting-started/) guide.
