### ISSUE TITLE
RPython compatible

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vlasovskikh/funcparserlib#37]
```
I'm not sure how difficult this would be
but it would be nice to be able to use 
funcparserlib along with RPython.
```

Original issue reported on code.google.com by `prolo...@shortcircuit.net.au` on 25 Jul 2013 at 12:25

**Comment by vlasovskikh** [comment]
No progress has been made for this issue.

**Comment by prologic** [comment]
Actually FYI I made some effort on porting funcparserlib to RPython and I believe I was successful in translating a parser written using funcparserlib. I'll have to dig up the code; but if I recall it only needed some regex imports swapped out.
