### ISSUE TITLE
Tutorial not working

### ISSUE THREAD

**Issue by sofianito** [vlasovskikh/funcparserlib#49]
Hi!

I'm getting an error at line 47: return reduce(lambda s, (f, x): f(s, x), list, z)

It complains about the ( before f

**Comment by patrickmesana** [comment]
Anyone using this project?

**Comment by infectious** [comment]
I asked someone smarter than me and he said to change that line to:

`return reduce(lambda x, y: y[0](x, y[1]), list, z)`

**Comment by escalonn** [comment]
The line as written works in Python 2.x. But lambda parameter tuple unpacking was [removed in Python 3](https://www.python.org/dev/peps/pep-3113/). The 
version with x and y is the equivalent way to write it in Python 3 and also works in Python 2.
