### ISSUE TITLE
funcparserlib 0.3.6 install fails

### ISSUE THREAD

**Issue by amal-khailtash** [vlasovskikh/funcparserlib#71]
Installation via pip with Python 3.10.0 fails with:

`error in funcparserlib setup command: use_2to3 is invalid.`

**Comment by bruno-at-bareos** [comment]
see issue#70 with pip install funcparserlib==1.0.0a0 it will work ....

**Comment by amal-khailtash** [comment]
Thank you!  That fixes the issue.
